logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

spring:
  rabbitmq:
    host: 124.221.121.147 #主机地址
    port: 5672 #服务端口
    virtual-host: / #虚拟主机
    username: itcast #用户名
    password: 123321 #密码