logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

spring:
  rabbitmq:
    password: 123321
    username: itcast
    virtual-host: /
    port: 5672
    host: 124.221.121.147
    listener:
      simple:
        prefetch: 1 #消息预取上线
